### ISSUE TITLE
MY CUTIE PIE

### ISSUE THREAD

**Issue by gowrirepo** [gowrirepo/TLGowri#2]
cant delete
![888](https://github.com/gowrirepo/TLGowri/assets/167096063/9d1dadb2-e3e8-4c78-b4e3-d57d786deb8f)

**Comment by Figo1519** [comment]
**_kondrvan_**

**Comment by gowrirepo** [comment]
can you get this reply

**Comment by Figo1519** [comment]
yes

**Comment by Figo1519** [comment]
hoi

**Comment by gowrirepo** [comment]
i close na patti 
cant u c stupid

**Comment by gowrirepo** [comment]
![trashed-1669858572-20221029_175800](https://github.com/gowrirepo/TLGowri/assets/167096063/ec8cae26-2914-40a7-896b-8a4ff8b3f289)

**Comment by Figo1519** [comment]
nice
